//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yachts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int IdInvoice { get; set; }
        public int IdContract { get; set; }
        public bool Settled { get; set; }
        public int Sum { get; set; }
        public int SumIncludeVAT { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
